### ISSUE TITLE
Memory sentence does not show on iOS nor Android in night mode

### ISSUE THREAD

**Issue by jasonwilliams** [remiberthoz/anki-periodic-table-memory-pegs#124]
Do you know how to enable the memory sentence to show when flipping the card?

![8158DC75-EDAF-4925-B94A-7848C9F2555A](https://user-images.githubusercontent.com/936006/77235027-72089980-6baa-11ea-9afe-7d208a843883.png)

**Comment by jasonwilliams** [comment]
Just seen it’s ok on AnkiWeb

**Comment by remiberthoz** [comment]
Hey!

What Anki version do you have installed on iPad? It seems like the night mode is not implemented on your version of Anki: otherwise the backgrounds would be grey.

Can you confirm everything appears without the night mode activated?

**Comment by jasonwilliams** [comment]
Yes it works when night mode is off, is there a way of fixing it?

**Comment by remiberthoz** [comment]
I believe the problem comes from AnkiMobile on the AppStore.

Yet on the store page, it's indicated that version 2.0.56 and above does
support Anki 2.1.20 card rendering, hence night mode. Sadly, the iOS App is
not open source so I can't check the implementation details. I'll get in
touch with the developer!

In parallel, I will see if changing the text colour a little bit (from
black to dark gray) makes it readable in your situation!

Thanks for the report!

>

**Comment by jasonwilliams** [comment]
No problem, I’m using 2.0.59 iOS by the way.

**Comment by remiberthoz** [comment]
Ok apparently I was a bit fast. Because it works on AnkiDesktop, I assumed it was an issue in AnkiMobile, but it turns out the same issue arises on AnkiDroid...

**Comment by remiberthoz** [comment]
Fixed! The issue came from different implementations of night mode on desktop and mobiles version of Anki apps. The latest version `v2.3.1` should display consistent style on all platforms.

**Comment by jasonwilliams** [comment]
Thanks! That was a speedy fix,
Silly question, how do I apply the fix on the app? Do I have to delete the deck and reinstall it?

**Comment by jasonwilliams** [comment]
Hmm still the same for me, maybe I need to wait a bit if it’s downloading the older release

**Comment by jasonwilliams** [comment]
i downloaded 2.3.1 (from your github releases page) into the app, it’s still the same issue for me.

**Comment by remiberthoz** [comment]
Oh that's unexepected... let me check everything again!

**Comment by remiberthoz** [comment]
Sorry I can't reproduce this issue. I'm using Android only... On Android, when importing deck `v2.3.1` with `v2.3.0` already present, the template is corrected during the update.

A few ideas to fix the issue in your situation:

- Use Anki on a computer, login with your account and sync, download `v2.3.1`, sync again to push changes, sync from your iPad to download changes.
- Edit the css template directly on iPad. You should find *Edit Card Template* somewhere in the deck options. There is a css field where you can copy-paste the [stylesheet](https://raw.githubusercontent.com/remiberthoz/anki-periodic-table-memory-pegs/master/src/templates/stylesheet.css).

**Comment by remiberthoz** [comment]
I just submitted a question on AnkiSupport with respect to this issue: [link](https://anki.tenderapp.com/discussions/ankimobile/12099-night-mode-on-ankimobile-version-2059?unresolve=true). The dev is reactive so we will get feedback soon!

**Comment by remiberthoz** [comment]
@jasonwilliams, do you know which version of the deck you used when first reporting the issue? Was it `v2.3.0` or another?

If another, or if in doubts, I would like that you try to load `v2.3.0` into Anki. If I read the developer of AnkiMobile correctly, this version should work in iOS. If it does not, then I will reach to them again.

Thanks!

**Comment by remiberthoz** [comment]
Hey, I will consider this issue closed since there is no feedback since a long time. Let me know if there is still a problem!
